#ifndef PARSER_ERRORS
#define PARSER_ERRORS

#define BIT(x) 1 << x

// reserve 0 - 200 for parse op errors
typedef enum {
  ERROR_PARSE_NONE                = 1,
  ERROR_PARSE_EXPECTED_NUMBER     = BIT(1),
  ERROR_PARSE_NUMBER_OUT_OF_RANGE = BIT(2),
  ERROR_PARSE_EXPECTED_COMMA      = BIT(3),
  ERROR_PARSE_EXPECTED_X          = BIT(4),
  ERROR_PARSE_EXPECTED_Y          = BIT(5),
  ERROR_PARSE_EXPECTED_LPAREN     = BIT(6),
  ERROR_PARSE_EXPECTED_RPAREN     = BIT(7),
  ERROR_PARSE_EXPECTED_HASH       = BIT(8),
  ERROR_PARSE_EXPECTED_ACCUMULATOR= BIT(9),
  ERROR_PARSE_NULL_CURSOR         = BIT(10),

  ERROR_PARSE_BYTE_DIR_TOO_LONG   = BIT(11),

  ERROR_PARSE_EXPECTED_NAME       = BIT(12),
  ERROR_PARSE_UNEXPECTED_NAME     = BIT(13),
  ERROR_PARSE_EXPECTED_COLON      = BIT(14),

  ERROR_PARSE_UNSUPPORTED_ADDR_MODE = BIT(15),
} error_parse;

const char* parser_errors_str(error_parse code);

#endif
